language: python

os: "linux"

python:
  - "3.7"

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.0

before_install:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4842
  # Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

  # set UID to run docker service with
  - echo "UID=$(id --user)" > .env
jobs:
  include:
    - env: BUILD_TYPE=standard
      install:
        - docker-compose up -d --build

      script:
        - docker-compose exec caluma black --check .
        - docker-compose exec caluma flake8
        - docker-compose exec caluma gitlint --commits ${TRAVIS_BRANCH}..HEAD lint
        - docker-compose exec caluma ./manage.py makemigrations --check --dry-run --no-input
        - docker-compose exec caluma pytest --no-cov-on-fail --cov --create-db -vv
        - docker-compose exec caluma reuse lint
    - env:
        BUILD_TYPE=pipenv
        PIPENV_IGNORE_VIRTUALENVS=1
      install: python3 setup.py pipenv
      script: pipenv run pytest
    - env:
        BUILD_TYPE=package
      install:
        - echo UID=$(id -u) > .env
        - echo ENV=dev >> .env
        - docker-compose up -d db
        - rm -rf dist/
        - python -m pip install --upgrade pip
        - pip install setuptools wheel
        - python setup.py bdist_wheel
        - pip install dist/caluma-*.whl
        - pip install -r requirements-dev.txt
      script: pytest --no-cov-on-fail --cov --create-db -vv
